CONDA_BUILD_SYSROOT:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
MACOSX_DEPLOYMENT_TARGET:
  - "11.0"
CONDA_SUBDIR:
  - osx-arm64
# rattler-build build -r ./recipes/msgs/recipe.yaml -c conda-forge -c robostack-jazzy
