package:
  name: unilabos
  version: "0.12.1"

source:
  path: ../..

build:
  noarch: python
  script: |
    {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
#    {{ PYTHON }} clean_build_dir.py

requirements:
  host:
    - python ==3.12.13
    - pip
  run:
    - python >=3.12,<3.13

test:
  imports:
    - unilabos
