apiVersion: v1
kind: Service
metadata:
  name: signoz-otel
  namespace: xiongyanfei
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: signoz-ingester
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc
      nodePort: 30157
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: otlp-http
      nodePort: 30158
