package:
  name: ros-jazzy-unilabos-msgs
  version: 0.12.0
source:
  path: ../../unilabos_msgs
  target_directory: src

build:
  script:
  - if: win
    then:
    - copy %RECIPE_DIR%\bld_ament_cmake.bat %SRC_DIR%
    - call %SRC_DIR%\bld_ament_cmake.bat
  - if: unix
    then:
    - cp $RECIPE_DIR/build_ament_cmake.sh $SRC_DIR
    - bash $SRC_DIR/build_ament_cmake.sh

about:
  repository: https://github.com/deepmodeling/Uni-Lab-OS
  license: BSD-3-Clause
  description: "ros-jazzy-unilabos-msgs provides the ROS 2 Jazzy message definitions for Uni-Lab-OS."

requirements:
  build:
  - ${{ compiler('cxx') }}
  - ${{ compiler('c') }}
  - python ==3.12.13
  - numpy >=2,<3
  - if: build_platform != target_platform
    then:
    - pkg-config
    - cross-python_${{ target_platform }}
  - if: linux and x86_64
    then:
    - sysroot_linux-64 ==2.17
  - ninja
  - setuptools
  - cython
  - cmake
  - if: unix
    then:
    - make
    - coreutils
  - if: osx
    then:
    - tapi
  - if: win
    then:
    - vs2022_win-64
  host:
  - python ==3.12.13
  - python_abi 3.12.* *_cp312
  - numpy >=2,<3
  - pip
  - if: build_platform == target_platform
    then:
    - pkg-config
  - robostack-jazzy::ros-jazzy-action-msgs
  - robostack-jazzy::ros-jazzy-ament-cmake
  - robostack-jazzy::ros-jazzy-ament-lint-auto
  - robostack-jazzy::ros-jazzy-ament-lint-common
  - robostack-jazzy::ros-jazzy-ros-environment
  - robostack-jazzy::ros-jazzy-ros-workspace
  - robostack-jazzy::ros-jazzy-rosidl-default-generators
  - robostack-jazzy::ros-jazzy-std-msgs
  - robostack-jazzy::ros-jazzy-geometry-msgs
  - robostack-jazzy::ros2-distro-mutex 0.15.* jazzy_*
  run:
  - python >=3.12,<3.13
  - python_abi 3.12.* *_cp312
  - robostack-jazzy::ros-jazzy-action-msgs
  - robostack-jazzy::ros-jazzy-ros-workspace
  - robostack-jazzy::ros-jazzy-rosidl-default-runtime
  - robostack-jazzy::ros-jazzy-std-msgs
  - robostack-jazzy::ros-jazzy-geometry-msgs
  - robostack-jazzy::ros2-distro-mutex 0.15.* jazzy_*
  - if: osx and x86_64
    then:
    - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
